webtalk_init -webtalk_dir C:/Users/alhinai/GitHub/CBNS/HW_implementation/HW_implementation.sim/sim_1/behav/xsim/xsim.dir/addComplex_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb  9 23:18:48 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7845a586-8393-4fc5-99eb-2fc0d26d21a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d6949de4c81443098c8764400bc96eab" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "77" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "47624050 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "49064_KB" -context "xsim\\usage"
webtalk_transmit -clientid 858000972 -regid "" -xml C:/Users/alhinai/GitHub/CBNS/HW_implementation/HW_implementation.sim/sim_1/behav/xsim/xsim.dir/addComplex_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/alhinai/GitHub/CBNS/HW_implementation/HW_implementation.sim/sim_1/behav/xsim/xsim.dir/addComplex_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/alhinai/GitHub/CBNS/HW_implementation/HW_implementation.sim/sim_1/behav/xsim/xsim.dir/addComplex_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
